name: restart

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: nq
          timeout: 8m